cidr_block            = "172.0.0.0/16"
aws_region            = "ap-south-1"
aws_secret_key        = ""
aws_access_key        = ""
private_subnets_count = 2
public_subnets_count  = 2
availability_zones    = ["ap-south-1a", "ap-south-1b"]
public_subnets        = "pub"
public_key            = ""
